version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: onestopjustice-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - onestopjustice-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API Server
  backend:
    image: prithuanan/onestopjustice-backend:latest
    container_name: onestopjustice-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3001}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - PINATA_API_Key=${PINATA_API_Key}
      - PINATA_API_Secret=${PINATA_API_Secret}
      - PINATA_JWT=${PINATA_JWT}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - AMOY_RPC_URL=${AMOY_RPC_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - ETH_KEY=${ETH_KEY}
      - BLOCKCHAIN_TEST_MODE=${BLOCKCHAIN_TEST_MODE:-false}
    ports:
      - "3001:3001"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - onestopjustice-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend with Nginx
  frontend:
    image: prithuanan/onestopjustice-frontend:latest
    container_name: onestopjustice-frontend
    restart: unless-stopped
    ports:
      - "5000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - onestopjustice-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  onestopjustice-network:
    driver: bridge
